name: atlastime
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  onboarding_overlay: ^3.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0
  geolocator: ^10.1.0
  camera: ^0.10.5+9
  http: ^0.13.6
  path_provider: ^2.1.2
  device_info_plus: ^11.5.0
  permission_handler: ^11.0.0
  intl: any
  image: ^4.0.17
  image_picker: ^1.0.7
  flutter_native_splash: ^2.3.2
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo_atlas.png
    - assets/icono.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icono.png"

# ðŸŸ© Mueve esta secciÃ³n completamente fuera del bloque 'flutter'
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_atlas.png
  android: true
  ios: true
  fullscreen: true
